CREATE TABLE vehicle (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    vehicle VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    "year" INT NOT NULL,
    description CLOB,
    sold BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE
    seq_vehicles
    START WITH 1
    INCREMENT BY 1;